version: "2.1"

services:
  loragtwpktfwd:
    restart: always
    build:
      context: loragtwpktfwd
      args:
        - LORA_REGION=US915
        - LORA_UDP=1680 #default "1680"
        #- SPI_SPEED=8000000 #default 2000000
        - PIN_RESET=17
        - MINER_URL=3.131.80.208
    privileged: true

volumes:
  miner-data:
  miner-log:
